### PR TITLE
Feature refactor

### PR DESCRIPTION
**Pull request by codlab**
This branch is mainly here to provide multiple improvements regarding evolutions.

- greendao and greendaoGenerator : _improve the way the models are persistently saved with less codes, etc..._

- retrofit : _call the webservice easily, improve code efficiency and testings_

- mutex : _a simple inter processes mutex library for Android, was mainly here to help thread safe feature for db access._

- butterknife : _view injection, less codes, few overhead_

Other modification :
- add possibility to change the world language (it is impossible to log from a french account to an english server -- Modification according to webscrap to be done certainly) - or simply revert the modifications and state that the user must use the English servers only

- Cookies are for now non persistant in the OgameAgent, a replug with the CookieManager must be done (possibly also by changing the schema mandatories fields since some cookies are with non mandatory fields)

improvements to come in futures release in this branch:
- complete UI rework and workflow
- otto EventBus library

### CODE REVIEW

**Comment by afwang** [comment]
Wow, this is amazing. Thanks a lot! How did you find out about this project? I'll be reviewing this for a while (quite a number of new things to me).

**Comment by codlab** [comment]
i was looking for an android client for ogame but ... since GF is quite slow in the matter...

I found this github repo and btw, was disappointed not finding any enhanced client :p so here is my part on it.

I made major modification from the given list :

- Jsoup library to simplify request on the document obtained
- otto EventBus to grab dynamic feature to the app

There is still an issue if you use a non english server. I can't connect to my french account

**Comment by afwang** [comment]
So far, everything looks good, but I do have a request: Can you add the GPLv3 header to the top of the new files?

**Comment by codlab** [comment]
the headers have been added

**Pull request merged**
